# Generated by Django 4.0.5 on 2022-08-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_alter_product_description_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='front_camera',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='фронтальная камера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_camera',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='основная камера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='memory',
            field=models.PositiveIntegerField(verbose_name='память'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.PositiveIntegerField(verbose_name='оперативная память'),
        ),
    ]
